### ISSUE TITLE
When will the library be released?

### ISSUE THREAD

**Issue by vasticles** [lyft/Kronos-Android#2]
Hi! I was really looking forward to using this library. However, I came across an unexpected roadblock. There is no version information available - https://github.com/lyft/Kronos-Android/releases. I couldn't find it on maven either. So I'm not sure how I can pull it down with gradle. When will the library be released?

Thanks!

**Comment by antonis-bc** [comment]
Hi! What i did is to clone the library and add as a local module to my project.

**Comment by latas** [comment]
Hey! What I did is to clone the library and add it as a local module to my project! Hope that helps

**Comment by vasticles** [comment]
> Hey! What I did is to clone the library and add it as a local module to my project! Hope that helps

I ended up doing the same. Thanks for the tip.

**Comment by vangelishat** [comment]
Hi. When adding `implementation "com.lyft.kronos:kronos-android:$latest_version"` to the build.gradle file under dependencies,
I get the following error: Failed to resolve: com.lyft.kronos:kronos-android:v1.0.0

**Comment by amphora001** [comment]
We are still incubating the code inside the Lyft app. We're seeing a small but noticeable amount of logs with suspicious timing data. We want to spend some time to ensure it's not a bug in Kronos before releasing 1.0.0. So in the mean time, please clone the library as @latas suggested. Thanks!

**Comment by ameliariely** [comment]
I'm excited to announce that `v0.0.1-alpha09` is available on Maven Central. Thank you for your interest and patience.
