### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by aornano** [lyft/Kronos-Android#24]
I've always the same error in dependencies:
`ERROR: Failed to resolve: com.lyft.kronos:kronos-android:0.0.1-alpha05
`
This library is unusable.

**Comment by ameliariely** [comment]
We are fixing the publishing pipeline. I will update as soon as we have a release.

**Comment by ameliariely** [comment]
Hey @aornano, try again with `v0.0.1-alpha09`. It's up on Maven Central.

**Comment by ameliariely** [comment]
Closing until further notice
