### ISSUE TITLE
Can't import library

### ISSUE THREAD

**Issue by proft** [lyft/Kronos-Android#26]
Hi!
I can't import library using File -> New > Import module ... > Source directory > 
kronos-android [+] Import
kronos-java [+] Import

After that I have following issue:

``Could not read script '/Users/proft/Projects/Android/Sandbox/gradle/publish-android.gradle' as it does not exist.``

What should I do?

**Comment by wdziemia** [comment]
Is the pre-release version being hosted on something outside of maven-central?

**Comment by artem-zinnatullin** [comment]
0.0.1-alpha09 is now available on Maven Central https://search.maven.org/search?q=com.lyft.kronos

Sorry for confusion :)

Please feel free to comment/reopen if you still have issues!
