### ISSUE TITLE
Suggestion: Add instructions to include and use library in Java-only Android project

### ISSUE THREAD

**Issue by agforte** [lyft/Kronos-Android#32]
I have written an app for Android in Java. It would be helpful to know how to install and use this Kotlin library in my Java Android app.

**Comment by arturdryomov** [comment]
I believe the installation is covered in the readme file under suggested changes to `build.gradle` files. Calling the API from Java doesn’t differ much from calling it from Kotlin due to the interop Kotlin provides.
