### ISSUE TITLE
Default NTP hosts?

### ISSUE THREAD

**Issue by agforte** [lyft/Kronos-Android#33]
Nowhere in the documentation it says what are the default NTP hosts used. Could you please add it so that users can choose if to use them or replace them with others?

**Comment by HappyDr0id** [comment]
Looking at the implementation, the default hosts seem to be there: https://github.com/lyft/Kronos-Android/blob/19642bb31950ad7ffca67625bff644dfce281fd2/kronos-java/src/main/java/com/lyft/kronos/DefaultParam.kt#L6

**Comment by arturdryomov** [comment]
This detail is mentioned in the readme file at this point.
