### ISSUE TITLE
Migrate to Androidx?

### ISSUE THREAD

**Issue by kenshin171** [lyft/Kronos-Android#41]
Hi is it possible for Kronos to move to useing androidx dependencies?
This is one of the only handful of libs that still require me to use jetifier.

```
* com.lyft.kronos:kronos-android:0.0.1-alpha09
  \-- com.lyft.kronos:kronos-java:0.0.1-alpha09
   \-- com.android.support:support-annotations:28.0.0
```

**Comment by arturdryomov** [comment]
`0.0.1-alpha10` was shipped without support dependencies, meaning that AndroidX is irrelevant for Kronos at this point.
