### ISSUE TITLE
v0.0.1-alpha10 same as v0.0.1-alpha09

### ISSUE THREAD

**Issue by developer-dmp** [lyft/Kronos-Android#54]
Has anyone else seen this? I recently updated my `build.gradle` implementation to the newest version and when I rebuild the project/perform gradle sync, I see the **alpha10** library in my project, but checking out the source reveals the files are in the same state as they were in the **alpha09** version.
![Screen Shot 2021-02-09 at 12 44 18 PM](https://user-images.githubusercontent.com/31141114/107404823-a80d7f80-6ad4-11eb-8523-1b05ad26643c.png)
![Screen Shot 2021-02-09 at 12 44 43 PM](https://user-images.githubusercontent.com/31141114/107404824-a80d7f80-6ad4-11eb-96a9-fbe138211f02.png)
![Screen Shot 2021-02-09 at 12 44 52 PM](https://user-images.githubusercontent.com/31141114/107404825-a80d7f80-6ad4-11eb-95ee-d892b033261c.png)

Some screenshots of the project and the files that I saw were modified in the release notes but seemed to not be modified in the new **alpha10** package.

Checking the maven repo shows **alpha10** being the latest version too so a little confused here.

**Comment by arturdryomov** [comment]
Not sure about your comparison criteria but neither `DefaultParam` nor `AndroidClockFactory` were changed in the `v0.0.1-alpha10`. [At least it seems so from the diff](https://github.com/lyft/Kronos-Android/compare/v0.0.1-alpha09...v0.0.1-alpha10).

**Comment by developer-dmp** [comment]
Yup I figured this had to be my fault. When looking at the latest release, there is a link to commits that have happened _**since this release**_ and I was looking at that diff. My apologies and thanks for the response!
